import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { 
    MatButtonModule, 
    MatIconModule, 
    MatFormFieldModule, 
    MatInputModule,
    MatDatepickerModule,
    MatSliderModule,
    MatNativeDateModule,
    MatCheckboxModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatTabsModule,
    MatCardModule,
    MatSelectModule,
    MatProgressSpinnerModule,
    MatDialogModule,
    MatExpansionModule,
    MatChipsModule,
    MatTooltipModule,
    MatAutocompleteModule,
    MatStepperModule,
    MatTableModule,
    MatBadgeModule,
    MatMenuModule,
    MatSnackBarModule,
    MatPaginatorModule
} from '@angular/material';

@NgModule({
    declarations: [],
    imports: [ 
        CommonModule,
        MatButtonModule,
        MatIconModule, 
        MatFormFieldModule, 
        MatInputModule,
        MatDatepickerModule,
        MatSliderModule,
        MatNativeDateModule,
        MatCheckboxModule,
        MatSidenavModule,
        MatToolbarModule,
        MatListModule,
        MatTabsModule,
        MatCardModule,
        MatSelectModule,
        MatProgressSpinnerModule,
        MatDialogModule,
        MatExpansionModule,
        MatChipsModule,
        MatTooltipModule,
        MatAutocompleteModule,
        MatStepperModule,
        MatTableModule,
        MatBadgeModule,
        MatMenuModule,
        MatSnackBarModule,
        MatPaginatorModule
    ],
    exports: [
        MatButtonModule,
        MatIconModule, 
        MatFormFieldModule, 
        MatInputModule,
        MatDatepickerModule,
        MatSliderModule,
        MatNativeDateModule,
        MatCheckboxModule,
        MatSidenavModule,
        MatToolbarModule,
        MatListModule,
        MatTabsModule,
        MatCardModule,
        MatSelectModule,
        MatProgressSpinnerModule,
        MatDialogModule,
        MatExpansionModule,
        MatChipsModule,
        MatTooltipModule,
        MatAutocompleteModule,
        MatStepperModule,
        MatTableModule,
        MatBadgeModule,
        MatMenuModule,
        MatSnackBarModule,
        MatPaginatorModule
    ],
})
export class MaterialModule {}